name: ParallelSequntiel #name
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: |
          echo "A Demo build"
  build2:
    runs-on: ubuntu-latest
    steps:
      - name: Build2 Step
        run: |
          echo "A Demo build2"
  test:
    runs-on: ubuntu-latest    
    steps:
      - name: Test Phase
        run: |
          echo "Running the Testing"
  deploy:
    needs: [test,build]
    runs-on: ubuntu-latest    
    steps:
      - name: Deploy Phase
        run: |
          echo "Deploy Phase is working"

  deployParallel:
    needs: [build, build2]
    runs-on: ubuntu-latest
    steps:
      - name: DeployParallel Phase
        run: |
          echo "Deploy Phase is working"
